library(shiny)
library(tidyverse)
library(ggplot2)
library(plotly)
library(lubridate)
library(shinydashboard)
source("modules/data_cleaning.R")
cleaned_data$Year <- as.numeric(cleaned_data$Year)
cleaned_data <- cleaned_data %>%
  filter(!is.na(Cases), !is.na(Deaths))